# This is a basic workflow to help you get started with Actions

name: Event Trigger Workflow
on:
  # Triggers when pull request / issues get raised in a specific repository
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    types: [labeled]
  issues:
    types: [labeled]
jobs:
  # This workflow contains a single job called "build"
  build:
    # If the triggers are labelled as agenda then we proceed to build this job
    if: github.event.label.name == 'agenda'
    runs-on: ubuntu-latest
    steps:
      # This step runs when the event is pull_request labeled agenda
      - name: pull request with label agenda
        if: github.event_name == 'pull_request'
        run: |
          echo [${{github.event.pull_request.html_url}}],[${{github.event.sender.login}}] >> authors.txt
      #This step runs when the event is issues labeled agenda
      - name: issues with label agenda
        if: github.event_name == 'issues'
        run: |
          echo [${{github.event.issue.html_url}}],[${{github.event.sender.login}}] >> authors.txt
      #This step runs to upload the artifact containing the author and pull request 
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: list of authors and their issues and pull request
          path: authors.txt
          continue-on-error: true

